### ISSUE TITLE
Error with miting

### ISSUE THREAD

**Issue by mdergueche** [metaplex-foundation/python-api#36]
Hi community, 

So I'm trying to mint an NFT on Solana using your library but I'm getting an error at metada function. Here the stuck

File "/python-api/api/metaplex_api.py", line 77, in mint
tx, signers = mint(api_endpoint, self.keypair, contract_key, dest_key, link, supply=supply)
File "/python-api/metaplex/transactions.py", line 186, in mint
metadata = get_metadata(client, mint_account)
File "/python-api/metaplex/metadata.py", line 182, in get_metadata
data = base64.b64decode(client.get_account_info(metadata_account)['result']['value']['data'][0])
TypeError: 'NoneType' object is not subscriptable 

also how I know the fee on the network to mint the NFT? I check the library, there is no such function as such. It would be great to add it before deciding to mint the contract as such.

Your help will be really appreciated.

**Comment by mdergueche** [comment]
somehow I managed to mint one contract on the mainnet beta without changing anything from my end!

but today trying again, I'm facing the same error!!! please help.

**Comment by nurav97** [comment]
#8

**Comment by andeskis** [comment]
I also have an issue with the minting where its value is None

Deploy: {'jsonrpc': '2.0', 'result': '4PYzUAWcwDVEkryJn4XdXoj8JzSyN6yS14Tw3YM8oAaBZayqiKotP2a7XtyzaL2PBzpbrSn17emtJjPGrxF4QLVz', 'id': 2, 'contract': '8WpJDw7QPo9T8ZWsVK6wLjHypMRWN7tmKuvrth31ePLy', 'status': 200}

mint_key
8WpJDw7QPo9T8ZWsVK6wLjHypMRWN7tmKuvrth31ePLy

metadata_account
HVZ9XjamjRhmQwqaaPgepy6FxoPFHFqts1NgbJgAe85C

acc_info
{'jsonrpc': '2.0', 'result': {'context': {'slot': 108802316}, 'value': None}, 'id': 13}

Traceback (most recent call last):
  File "C:\Users\ander\Documents\code\solana\metapliex-example\python-api\api.py", line 161, in <module>
    test()
  File "C:\Users\ander\Documents\code\solana\metapliex-example\python-api\api.py", line 127, in test
    print(get_metadata(client, contract))
  File "C:\Users\ander\Documents\code\solana\metapliex-example\python-api\metaplex\metadata.py", line 192, in get_metadata
    acc_info_resp = acc_info['result']['value']['data'][0]
TypeError: 'NoneType' object is not subscriptable

**Comment by PixusMetaverse** [comment]
Not working either - have the same issue since this week

**Comment by mdergueche** [comment]
it is a shame. No support at all. some of users have managed to make it work!

**Comment by JeffryCA** [comment]
+1 I have the same problem

**Comment by soliblue** [comment]
@jarry-xiao Can you please support?

**Comment by JoseLuisDavila** [comment]
any solution ???

**Comment by nurav97** [comment]
They have stopped the development of this python API also no one supports in their discord we had to switch to their js SDK that might be the best bet
